### ISSUE TITLE
Division by Zero

### ISSUE THREAD

**Issue by jotafurtado** [Craytor/lumen-status#2]
I'm getting this error!

![captura de tela 2015-05-05 as 21 29 29](https://cloud.githubusercontent.com/assets/748350/7485548/f7c61508-f36d-11e4-839d-ac2f910efa52.png)

**Comment by Craytor** [comment]
@jotafurtado Thanks! I'll take a look and get a fix pushed out within the next hour.

**Comment by Craytor** [comment]
@jotafurtado Are you running on my latest commit? If not, please update.

**Comment by jotafurtado** [comment]
Yep, I'm running at latest commit. Just puled master now, same error.
![captura de tela 2015-05-05 as 22 37 22](https://cloud.githubusercontent.com/assets/748350/7486175/88e6d65e-f377-11e4-88b4-18fdfacf9891.png)

**Comment by Craytor** [comment]
Can you comment an image again like you did when you open the issue? The line numbers are not adding up.

Sent from Outlook




On Tue, May 5, 2015 at 6:39 PM -0700, "Jota Furtado" <notifications@github.com> wrote:












Yep, I'm running at latest commit. Just puled master now, same error.

**Comment by Craytor** [comment]
@jotafurtado Alright, pull in my latest changes (commit 891d024). That should work, but I need to identify the correct way to fix the problem.

Update: I've done a few commits since I originally wrote this, so I edited the commit reference above.

**Comment by jotafurtado** [comment]
Bug fixed! Thank you, now its working perfectly!

**Comment by Craytor** [comment]
@jotafurtado Sweet! Glad I could get that fixed, I'll go back and clean up the code.

**Comment by Craytor** [comment]
Commit 357c320 closes this issue.
